hasker/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from . import views


app_name = 'api'

urlpatterns = [
    # API Root
    path('', views.api_root, name='api-root'),

    # Question
    path('questions/', views.QuestionsListView.as_view(), name='questions-list'),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name='question-detail'),
    path('questions/<int:pk>/answers/', views.AnswersListView.as_view(), name='question-answers-list'),
    path('questions/<int:pk>/vote/', views.QuestionVoteView.as_view(), name='question-vote'),

    # Answer
    path('answers/<int:pk>/', views.AnswerDetailView.as_view(), name='answer-detail'),
    path('answers/<int:pk>/vote/', views.AnswerVoteView.as_view(), name='answer-vote'),

    # Tag
    path('tags/', views.TagsListView.as_view(), name='tags-list'),
    path('tags/<int:pk>/questions', views.TagQuestionsListView.as_view(), name='tag-questions-list'),

    # Search
    path('search/', views.SearchListView.as_view(), name='search'),

    # Trending Questions
    path('trending/', views.TrendingQuestionsListView.as_view(), name='trending-questions'),

    # Auth
    path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    # obtain_auth_token - use post metod with data (username and password) for generate api token
    # example:
    # curl -X POST http://localhost:8000/api/v1/api-token-auth/ -d "username=admin&password=admin"
    # -H Authorization: Token {token}
]

hasker/question/urls.py
from django.urls import path

from . import views

app_name = 'question'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('ask/', views.AskView.as_view(), name='ask'),
    path('question/<slug:slug>/', views.QuestionView.as_view(), name='question'),

    path('vote/question/<int:pk>/', views.QuestionVoteView.as_view(), name='question-vote'),
    path('vote/answer/<int:pk>/', views.AnswerVoteView.as_view(), name='answer-vote'),
    path('mark/answer/<int:pk>/', views.AnswerMarkView.as_view(), name='answer-mark'),
    path('search/', views.SearchView.as_view(), name='search'),
]

hasker/question/models.py
import itertools
from urllib.parse import urlencode

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ObjectDoesNotExist
from django.db import models, transaction
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _


class QuestionManager(models.Manager):
    def new(self):
        return self.all().order_by('-pub_date')

    def popular(self):
        return self.all().order_by('-rating', '-pub_date')


class AnswerManager(models.Manager):
    def popular(self):
        return self.all().order_by('-rating', '-pub_date')


class VoteMixin:
    def vote(self, user, value=False):
        if self.author == user:
            return False
        with transaction.atomic():
            try:
                vote = self.votes.get(user=user)
                if vote.vote != value:
                    vote.delete()
                else:
                    return False
            except ObjectDoesNotExist:
                self.votes.create(user=user, vote=value)
            self.rating += 1 if value else -1
            self.save()
            return True


class Question(VoteMixin, models.Model):
    title = models.CharField(_('Title'), max_length=255)
    text = models.TextField(_('Question'))
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    slug = models.SlugField(unique=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField('Tag', related_name='question_tags')
    votes = GenericRelation('Vote', related_query_name='questions')
    rating = models.IntegerField(default=0)

    correct_answer = models.ForeignKey(
        'Answer',
        models.SET_NULL,
        blank=True,
        null=True,
        related_name='correct_answer'
    )

    # Manager
    objects = QuestionManager()

    def __str__(self):
        return self.title

    @property
    def has_answer(self):
        return self.correct_answer is not None

    def get_absolute_url(self):
        return reverse("question:question", kwargs={'slug': self.slug})

    def get_vote_url(self):
        return reverse("question:question-vote", kwargs={'pk': self.pk})

    @property
    def url(self):
        return self.get_absolute_url()

    def get_slug_max_length(self):
        return self._meta.get_field('slug').max_length

    @classmethod
    def is_slug_exists(cls, slug):
        return cls.objects.filter(slug=slug).exists()

    def slugify(self, string):
        max_length = self.get_slug_max_length()
        slug = orig = slugify(string)[:max_length]
        for x in itertools.count(1):
            if not self.is_slug_exists(slug):
                break
            slug = '{}-{}'.format(orig[:max_length - len(str(x)) - 1], x)
        return slug

    def save(self, tags=(), *args, **kwargs):
        if not self.pk:
            self.slug = self.slugify(self.title)
        super().save(*args, **kwargs)
        tag_objects = []
        for tag in tags:
            tag_object, _ = Tag.objects.get_or_create(name=tag)
            tag_objects.append(tag_object)
        self.tags.add(*tag_objects)


class Answer(VoteMixin, models.Model):
    text = models.TextField(_('Answer'))
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    votes = GenericRelation('Vote', related_query_name='answers')
    rating = models.IntegerField(default=0)

    # Manager
    objects = AnswerManager()

    def mark(self, user):
        with transaction.atomic():
            question = self.question
            if question.author != user or self.author == user:
                return False
            if question.has_answer:
                if question.correct_answer == self:
                    question.correct_answer = None
                else:
                    question.correct_answer = self
            else:
                question.correct_answer = self
            question.save()
            return True

    def get_vote_url(self):
        return reverse('question:answer-vote', kwargs={'pk': self.pk})

    def get_mark_url(self):
        return reverse('question:answer-mark', kwargs={'pk': self.pk})


class Tag(models.Model):
    name = models.CharField(_('Name'), max_length=50, unique=True)

    def __str__(self):
        return self.name

    def get_search_url(self):
        return '{}?{}'.format(reverse("question:search"), urlencode({'q': 'tag:' + self.name}))

    @property
    def url(self):
        return self.get_search_url()


class Vote(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    vote = models.BooleanField(default=False)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

hasker/question/forms.py
import re

from django.conf import settings
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import Question, Answer


class QuestionCreateForm(forms.ModelForm):
    tags = forms.CharField(
        required=False,
        help_text=_('Enter tags, separated by commas. Maximum {} tags'.format(settings.MAX_TAGS_LIMIT)),
    )

    class Meta:
        model = Question
        fields = ('title', 'text', 'tags',)

    def clean_tags(self):
        tags = self.cleaned_data.get('tags')
        tags = [t.strip() for t in tags.split(',')] if tags else []

        if len(tags) > settings.MAX_TAGS_LIMIT:
            raise ValidationError(_('The maximum number of tags is {}'.format(settings.MAX_TAGS_LIMIT)))

        for tag in tags:
            if not re.match(r'^[\w\@\.\+\-]+$', tag):
                raise ValidationError(_('Tag value may contain only English letters, numbers and @/./+/-/_ characters.'))

        return tags


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('text',)
        labels = {
            'text': _('Your answer'),
        }
        widgets = {
            'text': forms.Textarea(attrs={
                'rows': 3,
                'placeholder':'Enter your answer here...',
            }),
        }

hasker/question/views.py
from itertools import chain
from urllib.parse import urlencode

from django.conf import settings
from django.db.models import Q
from django.views import generic, View
from django.views.generic.list import MultipleObjectMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist, ImproperlyConfigured
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import JsonResponse, Http404, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from .models import Question, Answer, Tag
from .forms import QuestionCreateForm, AnswerForm
from .utils import new_answer_email_notify


class AskView(LoginRequiredMixin, generic.CreateView):
    form_class = QuestionCreateForm
    template_name = 'question/question_create.html'
    extra_context = {'title': 'Ask a question',
                     'max_tags_limit': settings.MAX_TAGS_LIMIT}

    def form_valid(self, form):
        question = form.save(commit=False)
        tags = form.cleaned_data['tags']
        question.author = self.request.user
        question.save(tags=tags)
        return redirect(question.url)


class QuestionView(MultipleObjectMixin, View):
    model = Question
    form_class = AnswerForm
    context_object_name = 'answers'
    paginate_by = settings.PAGINATE_ANSWERS
    template_name = 'question/question_detail.html'
    form = None

    def get(self, request, slug):
        self.form = self.form_class()
        self.question = get_object_or_404(self.model, slug=slug)
        return self.render_to_response(self.get_context_data())

    @method_decorator(login_required)
    def post(self, request, slug):
        self.form = form = self.form_class(request.POST)
        self.question = question = get_object_or_404(self.model, slug=slug)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.author = request.user
            answer.save()
            if request.user.pk != question.author.pk:
                new_answer_email_notify(request, question, answer)
            return redirect(question.url)
        return self.render_to_response(self.get_context_data())

    def get_queryset(self):
        return self.question.answer_set.popular()

    def get_context_data(self, **kwargs):
        object_list = self.get_queryset()
        context = super().get_context_data(object_list=object_list, **kwargs)
        context.update({
            'question': self.question,
            'form': self.form,
        })
        return context

    def render_to_response(self, context, **response_kwargs):
        return render(self.request, self.template_name,
                      context, **response_kwargs)


class IndexView(generic.ListView):
    context_object_name = 'questions'
    paginate_by = settings.PAGINATE_QUESTIONS
    template_name = 'question/question_list.html'


    def get_queryset(self):
        sort = self.request.GET.get('sort')
        if sort == 'popular':
            return Question.objects.popular()
        return Question.objects.new()

    def get_context_data(self):
        title = 'New Questions'
        sort = self.request.GET.get('sort')
        if sort == 'popular':
            title = 'Hot Questions'

        context = super().get_context_data()
        context.update({
            'title': title
        })
        return context


class SearchView(generic.ListView):
    context_object_name = 'questions'
    paginate_by = settings.PAGINATE_QUESTIONS
    template_name = 'question/question_search.html'
    extra_context = {'title': 'Search result'}

    def get_queryset(self):
        search_query = self.request.GET.get('q')
        if not search_query:
            return Question.objects.none()
        search_query = search_query[:255]

        if search_query.startswith('tag:'):
            # search tags
            search_tag_query = search_query[len('tag:'):]
            if not search_tag_query:
                return Question.objects.none()
            query = Q(tags__name__icontains=search_tag_query)
        else:
            query = Q(title__icontains=search_query) | Q(text__icontains=search_query)
            words = search_query.split()
            if words:
                for word in words:
                    query |= Q(title__icontains=word) | Q(text__icontains=word)
        return Question.objects.filter(query).distinct().order_by('-rating', '-pub_date')


class AnswerMarkView(View):
    model = Answer

    def post(self, request, pk):
        if request.user.is_authenticated:
            answer = get_object_or_404(self.model, pk=pk)
            success = answer.mark(request.user)
            return JsonResponse({'success': success})
        return HttpResponseForbidden()


class BaseVoteView(View):
    model = None

    def post(self, request, pk):
        model = self.model
        if not model:
            raise ImproperlyConfigured("Field 'model' must be specified.")

        if request.user.is_authenticated:
            value = True if request.POST.get('value') == 'true' else False
            instance = get_object_or_404(model, pk=pk)
            instance.vote(request.user, value)
            return JsonResponse({'rating': instance.rating})
        return HttpResponseForbidden()


class QuestionVoteView(BaseVoteView):
    model = Question


class AnswerVoteView(BaseVoteView):
    model = Answer

hasker/question/templates/question/question_create.html
{% extends 'layout.html' %}
{% load static %}

{% block title%}{% if title %}{{title}}{% else %}Ask{% endif %}{% endblock %}

{% block extrastyles %}
    <link rel="stylesheet" href="{% static 'css/tagify.css' %}">
{% endblock %}

{% block main %}
    <h2>{{title}}</h2>
    <br>
    {% include 'partials/form.html' %}
{% endblock %}

{% block extrascripts %}
    <script src="{% static 'js/jQuery.tagify.min.js' %}"></script>
{% endblock %}

{% block onbodyload %}
    $('[name=tags]').tagify({
        delimiters: ",",
        duplicates: false,
        maxTags: {{ max_tags_limit }},
    });
    $('form').submit( function() {
        let tags = $('#id_tags')[0].value;
        tags = JSON.parse(tags);

        let clear_tags = [];

        for (let i = 0; i < tags.length; i++) {
            clear_tags.push(tags[i].value);
        }
        $('#id_tags')[0].value = clear_tags.join(', ');
        return true;
    });
{% endblock %}

hasker/question/templates/question/question_detail.html
{% extends 'layout.html' %}
{% load form_tags %}

{% block title%}{% if question.title %}{{question.title}}{% else %}Question{% endif %}{% endblock %}

{% block main %}

    <!-- <h2>{{question.title}}</h2> -->

    <!-- Question - Question -->
    <div class="question-main-ask">
      <div class="row">
        <!-- logo block -->
        <div class="col-sm-2 mb-3">
          <div class="row">
            <!-- Avatar -->
            <div class="col-6 col-sm-12">
              <img data-src="holder.js/100x100" class="rounded mx-auto d-block avatar-img-150" alt="Avatar" data-holder-rendered="true" src="{{question.author.get_avatar_url}}">
            </div>
            <!-- Votes -->
            <div class="col-6 col-sm-12 text-center my-4">
              <a href="{{ question.get_vote_url }}" class="vote-up vote" title="Up vote">
                <i class="fas fa-chevron-up"></i></a><br>
              <b class="rating">{{ question.rating }}</b><br>
              <a href="{{ question.get_vote_url }}" class="vote-down vote" title="Down vote">
                <i class="fas fa-chevron-down"></i></a><br>
            </div>
          </div>
          <!-- /.row -->
        </div>
        <!-- Question -->
        <div class="col-sm-10">
            <h5><a href="{{ question.author.url }}">{{ question.author|title }}</a></h5>
            <h4>{{ question.title }}</h4>
            <p>{{ question.text }}</p>
            {% with question.tags.all as tags %}
                {% if tags %}
                    <p>Tags: {% for tag in tags %}<a href="{{ tag.url }}">{{tag}}</a> {% endfor %}</p>
                {% endif %}
            {% endwith %}
        </div>
      </div>
      <!-- /.row -->
    </div>
    <!-- /.question-main-ask -->

    {% if answers %}
        <hr>
        <!-- Question - Answers -->
        <div class="answer-list">
        {% for answer in answers %}
            {% include 'question/partials/answer.html' %}
        {% endfor %}
        </div>
    {% endif %}

    {% if is_paginated %}
        <!-- Question - Pagination -->
        {% include 'partials/pagination.html' %}
    {% endif %}

    {% if user.is_authenticated %}
        <hr>
        <!-- Question - Add Answer -->
        {% include 'partials/form.html' %}
    {% endif %}
{% endblock %}

hasker/question/templates/question/question_list.html
{% extends 'layout.html' %}

{% block title%}{% if title %}{{title}}{% else %}Questions{% endif %}{% endblock %}

{% block main %}
    <h2>{{title}}</h2>
    <p>
        <a href="{% url 'question:index' %}">New Questions</a> <span class="mx-2">|</span>
        <a href="{% url 'question:index' %}?sort=popular">Hot Questions</a>
    </p>
    <hr>
    {% if questions %}
        {% for question in questions %}
            {% include 'question/partials/question_list_item.html' %}
            <hr>
        {% endfor %}
        {% include 'partials/pagination.html' with page_url=paginate_url %}
    {% else %}
        <p>No Questions</p>
    {% endif %}
{% endblock %}

hasker/question/templates/question/question_search.html
{% extends 'layout.html' %}

{% block title%}{% if title %}{{title}}{% else %}Search result{% endif %}{% endblock %}

{% block main %}
    <h2>{{title}}</h2>
    <h6>Show result by: {{request.GET.q}}</h6>
    <hr>
    {% if questions %}
        {% for question in questions %}
            {% include 'question/partials/question_list_item.html' %}
            <hr>
        {% endfor %}
        {% include 'partials/pagination.html' with page_url=paginate_url %}
    {% else %}
        <p>No result...</p>
    {% endif %}
{% endblock %}