hasker/account/urls.py
from django.urls import path

from . import views


app_name = 'account'
urlpatterns = [
    # Auth
    path('singup/', views.SingUpView.as_view(), name='singup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    
    # User
    path('settings', views.UserEditView.as_view(), name='edit'),
    path('profile/<slug:username>/', views.UserProfileView.as_view(), name='profile')
]

hasker/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from . import views


app_name = 'api'

urlpatterns = [
    # API Root
    path('', views.api_root, name='api-root'),

    # Question
    path('questions/', views.QuestionsListView.as_view(), name='questions-list'),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name='question-detail'),
    path('questions/<int:pk>/answers/', views.AnswersListView.as_view(), name='question-answers-list'),
    path('questions/<int:pk>/vote/', views.QuestionVoteView.as_view(), name='question-vote'),

    # Answer
    path('answers/<int:pk>/', views.AnswerDetailView.as_view(), name='answer-detail'),
    path('answers/<int:pk>/vote/', views.AnswerVoteView.as_view(), name='answer-vote'),

    # Tag
    path('tags/', views.TagsListView.as_view(), name='tags-list'),
    path('tags/<int:pk>/questions', views.TagQuestionsListView.as_view(), name='tag-questions-list'),

    # Search
    path('search/', views.SearchListView.as_view(), name='search'),

    # Trending Questions
    path('trending/', views.TrendingQuestionsListView.as_view(), name='trending-questions'),

    # Auth
    path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    # obtain_auth_token - use post metod with data (username and password) for generate api token
    # example:
    # curl -X POST http://localhost:8000/api/v1/api-token-auth/ -d "username=admin&password=admin"
    # -H Authorization: Token {token}
]

hasker/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.documentation import include_docs_urls

from hasker.core import views as core_views


urlpatterns = [
    path('', include('hasker.account.urls')),
    path('', include('hasker.question.urls')),
    path('api/v1/', include('hasker.api.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path('403/', core_views.handler403),
        path('404/', core_views.handler404),
        path('500/', core_views.handler500),
    ] + urlpatterns

handler403 = core_views.handler403
handler404 = core_views.handler404
handler500 = core_views.handler500

hasker/question/urls.py
from django.urls import path

from . import views

app_name = 'question'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('ask/', views.AskView.as_view(), name='ask'),
    path('question/<slug:slug>/', views.QuestionView.as_view(), name='question'),

    path('vote/question/<int:pk>/', views.QuestionVoteView.as_view(), name='question-vote'),
    path('vote/answer/<int:pk>/', views.AnswerVoteView.as_view(), name='answer-vote'),
    path('mark/answer/<int:pk>/', views.AnswerMarkView.as_view(), name='answer-mark'),
    path('search/', views.SearchView.as_view(), name='search'),
]

hasker/account/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _

from .models import User
from .widgets import ClearableImageInput


class SingUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'avatar',)

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError(_('A user with that email address already exists.'))
        return email


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['avatar'].widget = ClearableImageInput()

    def clean_email(self):
        email = self.cleaned_data['email']
        if self.instance.email != email:
            if User.objects.filter(email=email).exists():
                raise ValidationError(_('A user with that email address already exists.'))
        return email

hasker/account/views.py
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView

from .forms import SingUpForm, UserEditForm
from .models import User


class SingUpView(CreateView):
    form_class = SingUpForm
    template_name = 'account/sing_up.html'
    success_url = reverse_lazy("account:login")
    redirect_authenticated_user = True

    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            return redirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)


class LoginView(LoginView):
    template_name = 'account/login.html'


class LogoutView(LogoutView):
    template_name = 'account/logout.html'


class UserEditView(LoginRequiredMixin, UpdateView):
    form_class = UserEditForm
    template_name = "account/profile_edit.html"

    def get_object(self, queryset=None):
        return self.request.user


class UserProfileView(DetailView):
    model = User
    template_name = "account/profile.html"
    context_object_name = "profile"
    slug_url_kwarg = "username"
    slug_field = "username"

hasker/api/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models import Q
from rest_framework import status
from rest_framework import generics
from rest_framework import permissions
from rest_framework.views import APIView
from rest_framework.exceptions import NotFound
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.reverse import reverse

from hasker.question.models import Answer, Question, Tag
from .serializers import (AnswerSerializer, QuestionSerializer,
                          QuestionsListSerializer, TagSerializer,
                          VoteSerializer)
from .paginators import (AnswerListPagination,
                         QuestionListPagination,
                         TagListPagination)
from .permissions import IsAuthorOrReadOnly


@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'questions': reverse('api:questions-list', request=request, format=format),
        'trending': reverse('api:trending-questions', request=request, format=format),
        'search': reverse('api:search', request=request, format=format),
        'tags': reverse('api:tags-list', request=request, format=format),
    })


class QuestionsListView(generics.ListAPIView):
    serializer_class = QuestionsListSerializer
    model = Question
    pagination_class = QuestionListPagination

    def get_queryset(self):
        sort = self.request.GET.get('sort')
        if sort == 'popular':
            return self.model.objects.popular()
        return self.model.objects.new()


class QuestionDetailView(generics.RetrieveDestroyAPIView):
    serializer_class = QuestionSerializer
    queryset = Question.objects.all()
    permission_classes = (permissions.IsAuthenticated, IsAuthorOrReadOnly,)


class AnswersListView(generics.ListAPIView):
    serializer_class = AnswerSerializer
    model = Answer
    pagination_class = AnswerListPagination

    def get_queryset(self):
        try:
            question = Question.objects.get(id=self.kwargs.get('pk'))
        except Question.DoesNotExist:
            raise NotFound()
        return question.answer_set.popular()


class AnswerDetailView(generics.RetrieveDestroyAPIView):
    serializer_class = AnswerSerializer
    queryset = Answer.objects.all()
    permission_classes = (permissions.IsAuthenticated, IsAuthorOrReadOnly,)


class TagsListView(generics.ListAPIView):
    serializer_class = TagSerializer
    queryset = Tag.objects.all().order_by('id')
    pagination_class = TagListPagination


class TagQuestionsListView(generics.ListAPIView):
    serializer_class = QuestionsListSerializer
    model = Tag
    pagination_class = QuestionListPagination

    def get_queryset(self):
        try:
            tag = self.model.objects.get(id=self.kwargs.get('pk'))
        except self.model.DoesNotExist:
            raise NotFound()
        return tag.question_tags.popular()


class SearchListView(generics.ListAPIView):
    serializer_class = QuestionsListSerializer
    model = Question
    pagination_class = QuestionListPagination

    def get_queryset(self):
        search_query = self.request.GET.get('q')
        if not search_query:
            return self.model.objects.none()
        search_query = search_query[:255]

        if search_query.startswith('tag:'):
            # search tags
            search_tag_query = search_query[len('tag:'):]
            if not search_tag_query:
                return self.model.objects.none()
            query = Q(tags__name__icontains=search_tag_query)
        else:
            query = Q(title__icontains=search_query) | Q(text__icontains=search_query)
            words = search_query.split()
            if words:
                for word in words:
                    query |= Q(title__icontains=word) | Q(text__icontains=word)
        return self.model.objects.filter(query).distinct().order_by('-rating', '-pub_date')


class TrendingQuestionsListView(generics.ListAPIView):
    serializer_class = QuestionsListSerializer
    queryset = Question.objects.popular()[:settings.TRENDING_QUESTIONS_LIMIT]


class BaseVoteView(APIView):
    serializer_class = VoteSerializer
    permission_classes = (permissions.IsAuthenticated,)
    model = None

    def post(self, request, pk):
        model = self.model
        if not model:
            raise ImproperlyConfigured("Field 'model' must be specified.")

        value = True if request.POST.get('value') == 'true' else False
        try:
            instance = model.objects.get(id=pk)
        except model.DoesNotExist:
            raise NotFound()
        vote = instance.vote(request.user, value)
        return Response({'rating': instance.rating, 'vote': vote}, status=status.HTTP_201_CREATED)


class QuestionVoteView(BaseVoteView):
    model = Question


class AnswerVoteView(BaseVoteView):
    model = Answer

hasker/core/views.py
from django.shortcuts import render
from django.views.decorators.csrf import requires_csrf_token


@requires_csrf_token
def handler403(request, exception=None):
    return render(request, 'errors/403.html', status=403)


@requires_csrf_token
def handler404(request, exception=None):
    return render(request, 'errors/404.html', status=404)


@requires_csrf_token
def handler500(request):
    return render(request, 'errors/500.html', status=500)

hasker/question/views.py
from itertools import chain
from urllib.parse import urlencode

from django.conf import settings
from django.db.models import Q
from django.views import generic, View
from django.views.generic.list import MultipleObjectMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist, ImproperlyConfigured
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import JsonResponse, Http404, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from .models import Question, Answer, Tag
from .forms import QuestionCreateForm, AnswerForm
from .utils import new_answer_email_notify


class AskView(LoginRequiredMixin, generic.CreateView):
    form_class = QuestionCreateForm
    template_name = 'question/question_create.html'
    extra_context = {'title': 'Ask a question',
                     'max_tags_limit': settings.MAX_TAGS_LIMIT}

    def form_valid(self, form):
        question = form.save(commit=False)
        tags = form.cleaned_data['tags']
        question.author = self.request.user
        question.save(tags=tags)
        return redirect(question.url)


class QuestionView(MultipleObjectMixin, View):
    model = Question
    form_class = AnswerForm
    context_object_name = 'answers'
    paginate_by = settings.PAGINATE_ANSWERS
    template_name = 'question/question_detail.html'
    form = None

    def get(self, request, slug):
        self.form = self.form_class()
        self.question = get_object_or_404(self.model, slug=slug)
        return self.render_to_response(self.get_context_data())

    @method_decorator(login_required)
    def post(self, request, slug):
        self.form = form = self.form_class(request.POST)
        self.question = question = get_object_or_404(self.model, slug=slug)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.author = request.user
            answer.save()
            if request.user.pk != question.author.pk:
                new_answer_email_notify(request, question, answer)
            return redirect(question.url)
        return self.render_to_response(self.get_context_data())

    def get_queryset(self):
        return self.question.answer_set.popular()

    def get_context_data(self, **kwargs):
        object_list = self.get_queryset()
        context = super().get_context_data(object_list=object_list, **kwargs)
        context.update({
            'question': self.question,
            'form': self.form,
        })
        return context

    def render_to_response(self, context, **response_kwargs):
        return render(self.request, self.template_name,
                      context, **response_kwargs)


class IndexView(generic.ListView):
    context_object_name = 'questions'
    paginate_by = settings.PAGINATE_QUESTIONS
    template_name = 'question/question_list.html'


    def get_queryset(self):
        sort = self.request.GET.get('sort')
        if sort == 'popular':
            return Question.objects.popular()
        return Question.objects.new()

    def get_context_data(self):
        title = 'New Questions'
        sort = self.request.GET.get('sort')
        if sort == 'popular':
            title = 'Hot Questions'

        context = super().get_context_data()
        context.update({
            'title': title
        })
        return context


class SearchView(generic.ListView):
    context_object_name = 'questions'
    paginate_by = settings.PAGINATE_QUESTIONS
    template_name = 'question/question_search.html'
    extra_context = {'title': 'Search result'}

    def get_queryset(self):
        search_query = self.request.GET.get('q')
        if not search_query:
            return Question.objects.none()
        search_query = search_query[:255]

        if search_query.startswith('tag:'):
            # search tags
            search_tag_query = search_query[len('tag:'):]
            if not search_tag_query:
                return Question.objects.none()
            query = Q(tags__name__icontains=search_tag_query)
        else:
            query = Q(title__icontains=search_query) | Q(text__icontains=search_query)
            words = search_query.split()
            if words:
                for word in words:
                    query |= Q(title__icontains=word) | Q(text__icontains=word)
        return Question.objects.filter(query).distinct().order_by('-rating', '-pub_date')


class AnswerMarkView(View):
    model = Answer

    def post(self, request, pk):
        if request.user.is_authenticated:
            answer = get_object_or_404(self.model, pk=pk)
            success = answer.mark(request.user)
            return JsonResponse({'success': success})
        return HttpResponseForbidden()


class BaseVoteView(View):
    model = None

    def post(self, request, pk):
        model = self.model
        if not model:
            raise ImproperlyConfigured("Field 'model' must be specified.")

        if request.user.is_authenticated:
            value = True if request.POST.get('value') == 'true' else False
            instance = get_object_or_404(model, pk=pk)
            instance.vote(request.user, value)
            return JsonResponse({'rating': instance.rating})
        return HttpResponseForbidden()


class QuestionVoteView(BaseVoteView):
    model = Question


class AnswerVoteView(BaseVoteView):
    model = Answer

hasker/templates/partials/form.html
<form {% if form_id %}id="{{ form_id }}"{% endif %}
    {% if class %}class="{{ class }}"{% endif %}
    method="{{ method|default:'post' }}"
    {% if action %}action="{{ action }}"{% endif %}
    {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>

    {% if not method == "get" %}{% csrf_token %}{% endif %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <i class="fas fa-exclamation-circle"></i> {{ error }}
            </div>
        {% endfor %}
    {% endif %}

    {% for field in form %}
        {% include 'partials/form_field.html'%}
    {% endfor %}

    <div class="form-group">
        <button class="btn btn-primary" type="submit" data-loading-text="'Saving...'">
            Submit
        </button>
    </div>
</form>

hasker/templates/partials/form_field.html
{% load form_tags %}

<div class="form-group">
    {% if field.is_hidden %}
        {{ field }}
    {% else %}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>

        {{ field | add_class:'form-control'}}

        {% if field.help_text %}
            <small class="form-text text-muted">
                {{ field.help_text|safe }}
            </small>
        {% endif %}

        {% if field.errors %}
            <div class="text-danger">{{ field.errors }}</div>
        {% endif %}

    {% endif %}
</div>

hasker/templates/partials/navbar.html
{% load static %}

<!-- NAVBAR -->
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-shadow">
    <div class="container">
        <a class="navbar-brand" href="{{homepage_url}}">
            Hasker
        </a>

        <button aria-controls="NavBar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#NavBar" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="NavBar">

            <!-- Search -->
            <form class="form-inline ml-auto my-1 mr-3" method="get" action="{% url 'question:search' %}">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-outline-dark" type="submit"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>

            <!-- Ask a Question -->
            {% if user.is_authenticated %}
                <div class="my-3 my-lg-0 d-lg-none">
                    <a class="btn btn-light" href="{% url 'question:ask' %}">Ask</a>
                </div>
            {% endif %}

            <!-- User Panel -->
            <ul class="navbar-nav my-1 ml-3">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <img src="{{ user.get_avatar_url }}" class="user-avatar-min" alt="avatar">
                        <a class="btn mr-2 btn-light" href="{{ user.url }}">
                            {{user.username|title}}
                        </a>
                        <a class="btn mr-2 btn-light" href="{% url 'account:logout' %}">
                            Log Out
                        </a>
                    {% else %}
                        <a class="btn mr-2 btn-light" href="{% url 'account:login'%}?next={{request.get_full_path}}">
                            Log In
                        </a>
                        <a class="btn mr-2 btn-light" href="{% url 'account:singup' %}">
                            Sing Up
                        </a>
                    {% endif %}
                </li>
            </ul>

        </div>
    </div>
</nav>
<!-- /.navbar -->

hasker/templates/partials/pagination.html
{% load pagination_tags %}

{% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="{% get_pagination_page_url page_obj.previous_page_number %}">
                    previous
                </a>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="{% get_pagination_page_url page_obj.next_page_number %}">
                    next
                </a>
            {% endif %}
        </span>
    </div>
{% endif %}

hasker/templates/partials/sidebar.html
{% load question_tags %}

{% if user.is_authenticated %}
    <div class="p-3">
        <a class="btn btn-outline-dark btn-block" href="{% url 'question:ask' %}">Ask</a>
    </div>
{% endif %}
<div class="p-3">
    {% trending_questions_block %}
</div>